<?php
/**
 * @file graph_services.module
 * TODO: Enter file description here.
 */

/**
 * Implements hook_menu().
 */
function graph_services_menu() {
    $items['graph/pie'] = array(
      'title' => 'Generate Pie Graph',
      'page callback' => 'graph_services_pie',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );

    $items['graph/bar'] = array(
      'title' => 'Generate Bar Graph',
      'page callback' => 'graph_services_bar',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );

    $items['graph/line'] = array(
      'title' => 'Generate Line Graph',
      'page callback' => 'graph_services_line',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );

    $items['graph/geochart'] = array(
      'title' => 'Generate Geo Chart',
      'page callback' => 'graph_services_geo',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );

    return $items;
}

function graph_services_geo() {
    $output = '';
    $data = $_REQUEST["data"];

    /*prepare data*/
    $data = $province_name = str_replace('-', ' ', $data);

    echo __graph_services_geo($data);
}

function __graph_services_geo($data) {
    $output = '';
    $output .= '
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        <script type="text/javascript">
         google.load("visualization", "1", {"packages": ["geochart"]});
         google.setOnLoadCallback(drawMarkersMap);

          function drawMarkersMap() {
          var data = google.visualization.arrayToDataTable([
            '.$data.'
          ]);

          var options = {
            region: "TH",
            displayMode: "markers",
            colorAxis: {colors: ["green", "blue"]},
            resolution: "provinces",
            magnifyingGlass: {enable: true, zoomFactor: 7.5},
          };

          var chart = new google.visualization.GeoChart(document.getElementById("chart_div"));
          chart.draw(data, options);
        };
        </script>
        <div id="chart_div" style="width: 900px; height: 500px;"></div>
    ';
    return $output;
}

function graph_services_line() {
    $name = $_REQUEST["name"];
    $data = $_REQUEST["data"];
    $width = $_REQUEST["width"];
    $height = $_REQUEST["height"];
    $label = $_REQUEST["label"];
    $vAxis = $_REQUEST["vaxis"];
    $hAxis = $_REQUEST["haxis"];

    echo __graph_services_line($label, $name, $data, $width, $height, $vAxis, $hAxis);
}

function __graph_services_line($label, $name, $data, $width, $height, $vAxis, $hAxis) {
    $output = '';
    $output .= '
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        <script type="text/javascript">
          google.load("visualization", "1", {packages:["corechart"]});
          google.setOnLoadCallback(drawChart);
          function drawChart() {
            var data = google.visualization.arrayToDataTable([
              '.$data.'
            ]);

            var options = {
              title: "'.$label.'",
              vAxis: {title: "'.$vAxis.'",  titleTextStyle: {color: "blue"}},
              hAxis: {title: "'.$hAxis.'",  titleTextStyle: {color: "blue"}},
              pointSize: 7,
            };

            var chart = new google.visualization.LineChart(document.getElementById("'.$name.'"));
            chart.draw(data, options);
          }
        </script>
        <div id="'.$name.'" style="width: '.$width.'; height: '.$height.';"></div>
    ';

    return $output;
}

function graph_services_bar() {
    $name = $_REQUEST["name"];
    $data = $_REQUEST["data"];
    $width = $_REQUEST["width"];
    $height = $_REQUEST["height"];
    $label = $_REQUEST["label"];

    echo __graph_services_bar($label, $name, $data, $width, $height);
}

function __graph_services_bar($graph_title, $name, $data, $width, $height) {
    $rows = explode(',', $data);
    $rows_count = 1;
    $cell = array();

    foreach ($rows as $key => $row) {
        if ($rows_count == 1) {
            $label = explode(':', $row);
        }
        else {
            $cell[] = explode(':', $row);
        }
        $rows_count++;
    }

    /*set first colum*/
    $data_json = '['.implode(',', $label).']';

    /*set data*/
    foreach ($cell as $key => $value) {
         $data_json .= ',['.implode(',', $value).']';
     }

    $output .= '
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        <script type="text/javascript">
            google.load("visualization", "1", {packages:["corechart"]});
            google.setOnLoadCallback(drawChart);
            function drawChart() {
                var data = google.visualization.arrayToDataTable([
                    '.$data_json.'
                ]);

                var options = {
                    title: "'.$graph_title.'",
                    vAxis: {title: "",  titleTextStyle: {color: "red"}}
                };

                var chart = new google.visualization.BarChart(document.getElementById("'.$name.'"));
                chart.draw(data, options);
            }
        </script>
        <div id="'.$name.'" style="width: 900px; height: 500px;"></div>';

    return $output;
}

function graph_services_pie() {
    /**
     * params = array(
     *      'name' => '',
     *      'data' => '',
     *      'width' => '',
     *      'height' => ''
     *  );
     */

    $name = $_REQUEST["name"];
    $data = $_REQUEST["data"];
    $width = $_REQUEST["width"];
    $height = $_REQUEST["height"];
    $label = $_REQUEST["label"];

    echo __graph_services_pie($label, $name, $data, $width, $height);
}

function __graph_services_pie($label, $name, $data, $width, $height) {
    $output = '';

    $param_data = explode(',', $data);
    $data_json = array();
    foreach ($param_data as $key => $value) {
        list($label_data,$scale) = explode(":", $value);
        $data_json[] = '["'.$label_data.'", '.$scale.']';
    }

    $output .= '
            <!--Load the AJAX API-->
            <script type="text/javascript" src="https://www.google.com/jsapi"></script>
            <script type="text/javascript">
                // Load the Visualization API and the piechart package.
                google.load("visualization", "1.0", {"packages":["corechart"]});

                // Set a callback to run when the Google Visualization API is loaded.
                google.setOnLoadCallback(drawChart);

                // Callback that creates and populates a data table,
                // instantiates the pie chart, passes in the data and
                // draws it.
                function drawChart() {
                    // Create the data table.
                    var data = new google.visualization.DataTable();
                    data.addColumn("string", "Topping");
                    data.addColumn("number", "Slices");
                    data.addRows(['.implode(',', $data_json).']);

                    // Set chart options
                    var options = {"legend":"right",
                                   "title":"'.$label.'",
                                   "width":'.$width.',
                                   "height":'.$height.',};

                    // Instantiate and draw our chart, passing in some options.
                    var chart = new google.visualization.PieChart(document.getElementById("'.$name.'"));
                    chart.draw(data, options);
                }
            </script>
            <div id="'.$name.'" style="width:640; height:480"></div>';

    return $output;
}
